// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bruyjdkmylypybyfsxff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJydXlqZGtteWx5cHlieWZzeGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjY5MTYsImV4cCI6MjA3NDkwMjkxNn0._wQeKseq7hKG_dSg1NXevL2KNH8HKz3u5QbPDs9Rd_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});