// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icybuplkenjblvhuqztc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWJ1cGxrZW5qYmx2aHVxenRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzM0MjIsImV4cCI6MjA2NjkwOTQyMn0.cmFMiZ6KtunQmUIX2K_amUCXgpUrr3e-jsNUIHayaO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});